[package]
name = "PolarsExcelReader"
version = "0.1.0"
edition = "2024"

[dependencies]
calamine = { git = "https://github.com/prophittcorey/calamine", branch = "fix/zip-3.0", features = ["dates"]}
polars = "0.49.1"
rayon = "1.10.0"
# polars = {version = "0.49.1",features = ["object"]}
